apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo 
  template:
    metadata:
      labels:
        app: argocd-demo 
    spec:
      containers:
      - image: engineeringveli/argocd-demo:ce013a2
        name: argocd-demo 
        ports:
        - containerPort: 8080
